### ISSUE TITLE
Errore pagine gialle

### ISSUE THREAD

**Issue by mello0303** [MishFdM/MIUI_V7_Italy#421]
Quando si accede a identifica numeri sconosciuti in applcazioni sistema, chiamate l'applicazione va in crash. Il log dell'errore

java.lang.RuntimeException: Unable to resume activity {com.miui.yellowpage/com.miui.yellowpage.activity.SettingActivity}: java.lang.IndexOutOfBoundsException: setSpan (-1 ... 16) starts before 0
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.access$800(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: java.lang.IndexOutOfBoundsException: setSpan (-1 ... 16) starts before 0
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java)
	at com.miui.yellowpage.utils.av.l(Unknown Source)
	at com.miui.yellowpage.utils.av.a(Unknown Source)
	at com.miui.yellowpage.ui.cL.gI(Unknown Source)
	at com.miui.yellowpage.ui.cL.I(Unknown Source)
	at com.miui.yellowpage.ui.cL.onResume(Unknown Source)
	at android.app.Fragment.performResume(Fragment.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java)
	at android.app.Activity.performResume(Activity.java)
	... 12 more

**Comment by ale8530** [comment]
Gentilmente puoi specificare meglio come manifesti questo bug?

Grazie

**Comment by liberato78** [comment]
Redmi note 2 a me nessun problema

**Comment by ale8530** [comment]
Infatti neanche io lo riscontro.

**Comment by mello0303** [comment]
Quando vado in applicazioni sistema, chiamate, dopo aver premuto identifica numei sconisciuti, compare il pop up dell'errore, nei dettagli trovo quanto riportato. L'errore compare anche quando mi chiama un numero sconosciuto e provo ad andare in dettagli. Il titolo dell'errore riporta che l'applicazione pagine gialle è andata in crash.
Avendo la rom multi forse dipende da quella rom?

**Comment by mello0303** [comment]
![screenshot_2016-01-10-14-49-48_com android settings](https://cloud.githubusercontent.com/assets/16482082/12221800/af6c4772-b7a9-11e5-80f2-c89f68ccabff.png)

**Comment by ale8530** [comment]
Scusami mello, ma io questa funzione "identifica numeri nascosti" non la trovo, mostrami screenshot dove andresti a premere questa funzione.
Grazie.

**Comment by mello0303** [comment]
Mi4c
![screenshot_2016-01-10-21-09-03_com android phone_1452456576565](https://cloud.githubusercontent.com/assets/16482082/12223709/96b61016-b7de-11e5-8426-da3fb8955804.jpg)

**Comment by ale8530** [comment]
Chiusa, questa funzione sul mio mi4c non c'è

**Comment by mello0303** [comment]
Ok sul tuo non c'è, ma sul mio si e non ce l'ho messa io l'opzione. Tra l'altro tradotta. Mi piacerebbe capire il perchè

**Comment by mello0303** [comment]
Non so se dipenda dalla versione o persino dall'operatore telefonico, ma cercando su google si parla dell'opzione e proprio sul mi 4c....mah, chiusa segnalazione un po troppo frettolosamente a mio avviso
